// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnDJlAEAxEe-Cu7SjcWH1tr_0ft62VBEA',
    appId: '1:588346618955:web:32d362db1f21e0ce1e09ce',
    messagingSenderId: '588346618955',
    projectId: 'shop-bb441',
    authDomain: 'shop-bb441.firebaseapp.com',
    storageBucket: 'shop-bb441.firebasestorage.app',
    measurementId: 'G-67S6SYETC0',
    databaseURL: 'https://shop-bb441-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCnkeeBmSb7di1QPbcaP8OxdDQW30Sjdc',
    appId: '1:588346618955:android:dc6206b7467c774d1e09ce',
    messagingSenderId: '588346618955',
    projectId: 'shop-bb441',
    storageBucket: 'shop-bb441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtfF_9G3r02rrRY-L5aa-NaSKYcizJ35I',
    appId: '1:588346618955:ios:4e0cb4f3025a46661e09ce',
    messagingSenderId: '588346618955',
    projectId: 'shop-bb441',
    storageBucket: 'shop-bb441.firebasestorage.app',
    iosBundleId: 'com.example.myshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtfF_9G3r02rrRY-L5aa-NaSKYcizJ35I',
    appId: '1:588346618955:ios:4e0cb4f3025a46661e09ce',
    messagingSenderId: '588346618955',
    projectId: 'shop-bb441',
    storageBucket: 'shop-bb441.firebasestorage.app',
    iosBundleId: 'com.example.myshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnDJlAEAxEe-Cu7SjcWH1tr_0ft62VBEA',
    appId: '1:588346618955:web:340965626e1163721e09ce',
    messagingSenderId: '588346618955',
    projectId: 'shop-bb441',
    authDomain: 'shop-bb441.firebaseapp.com',
    storageBucket: 'shop-bb441.firebasestorage.app',
    measurementId: 'G-P1QQR1DZXM',
  );
}
